services:
  valheim:
    image: lloesche/valheim-server:latest
    container_name: valheim-server
    restart: unless-stopped
    ports:
      - "2456-2458:2456-2458/udp"
    environment:
      - SERVER_NAME=puxadores
      - WORLD_NAME=puxadores
      - SERVER_PASS=secretvalheim
      - SERVER_PUBLIC=1
    volumes:
      - ./valheim/data:/config
      - ./valheim/server:/opt/valheim
