services:
  valheim:
    image: lloesche/valheim-server
    container_name: valheim-server
    restart: unless-stopped
    ports:
      - "2456-2458:2456-2458/udp"
    environment:
      - SERVER_NAME=puxadores
      - WORLD_NAME=puxadores
      - SERVER_PASS=puxadores
      - SERVER_PUBLIC=true
    volumes:
      - ./config:/config
